Avoid connection-pool-poisoning by leaning on the exception handling …
nikita-volkov/hasql-pool pull request #3
Opened 2019-01-11 13:04 UTC by mariatsji

…inside Data.Pool.withResource

Firstly, TY for your great SQL-libraries!

This PR resolves the issue of `Hasql.Connection.ConnectionError` being returned to the `Data.Pool`. `Data.Pool.withResource` uses an `onException` which is not invoked on a `Left` value, so in order for the pool resource destruction to take place, one has to actually throw an Exception.

2019-01-12 09:22 UTC, nikita-volkov requested changes
Good catch! I've added a few notes on your commits. Apart from them, can you also cover the solution with a test?

2019-01-12 09:22 UTC, nikita-volkov commented on hasql-pool.cabal
> +    base >= 4.0 && < 5
This is not required, since the Control.Exception module is already exported by "base-prelude".

2019-01-12 09:22 UTC, nikita-volkov commented on library/Hasql/Pool.hs
> +import Control.Exception (Exception, throwIO, catch)
Not required

2019-01-12 17:30 UTC, mariatsji commented on hasql-pool.cabal
> +    base >= 4.0 && < 5
ah, good. I was a bit worried by that one.

2019-01-12 17:34 UTC, mariatsji commented on library/Hasql/Pool.hs
> +import Control.Exception (Exception, throwIO, catch)
Perfect. I will try to include the hspec-test from my (stack-)project.

2019-01-15 06:52 UTC, merged

2019-01-15 06:57 UTC, nikita-volkov commented
Thanks. I've made some changes to your code to avoid the exception-wrapping with a lower-level integration with "resource-pool" and changed the test to not require the exposure of the constructor. See 86e5b85.